DROP TABLE IF EXISTS `caisis`.`BackboneMapping` ;

CREATE TABLE `caisis`.`BackboneMapping` (
  `OriginalProtocol` VARCHAR(100) NULL,
  `BackboneType` VARCHAR(20) NULL,
  `BackboneName` VARCHAR(45) NULL,
  `Anthracyclin` VARCHAR(45) NULL,
  `AnthracyclinDose` INT NULL,
  `BackboneAddOn` VARCHAR(100) NULL,
  `Intensity` VARCHAR(45) NULL );
  
INSERT INTO `caisis`.`backbonemapping`
    ( `OriginalProtocol`, `BackboneType`,   `BackboneName`, `Anthracyclin`, `AnthracyclinDose`, `BackboneAddOn`,   `Intensity` )
VALUES 
( 'XRT+AZA+HDAC', 'Multi', 'HiDAC', '', NULL, 'azacitidine,XRT', 'High' ),
( 'XRT + MEC', 'Multi', 'MEC', '', NULL, ',XRT', 'High' ),
( 'GO-MICE', 'Multi', 'MEC', '', NULL, ',gemtuzumab ozogamicin', 'High' ),
( 'CSA+MEC GO', 'Multi', 'MEC', '', NULL, ',gemtuzumab ozogamicin,cyclosporine', 'High' ),
( 'MECGOCSA(Ara-C)', 'Multi', 'MEC', '', NULL, ',gemtuzumab ozogamicin,cyclosporine', 'High' ),
( 'MEC', 'Multi', 'MEC', '', NULL, '', 'High' ),
( 'MEC+Plerixafor', 'Multi', 'MEC', '', NULL, ',plerixafor', 'High' ),
( 'IAVP', 'Multi', 'IAVP', '', NULL, '', 'High' ),
( '2674', 'Multi', 'IAP', '', NULL, '', 'High' ),
( '2674off', 'Multi', 'IAP', '', NULL, '', 'High' ),
( 'IAP', 'Multi', 'IAP', '', NULL, '', 'High' ),
( 'IAP+GO', 'Multi', 'IAP', '', NULL, ',gemtuzumab ozogamicin', 'High' ),
( 'IAP+sorafenib', 'Multi', 'IAP', '', NULL, ',sorafenib', 'High' ),
( 'IAP+Vincristine+Prednisone', 'Multi', 'IAVP', '', NULL, ' ', 'High' ),
( '2411(AS1411+HiDAC)', 'Multi', 'HiDAC', '', NULL, ',AS1411', 'High' ),
( 'Mito+HiDAC', 'Multi', 'HiDAC', ',mitoxantrone', NULL, ',mitoxantrone', 'High' ),
( 'XRT', 'Single', 'XRT', '', NULL, '', 'XRT' ),
( 'Temozolomide', 'Single', 'TEMOZOLOMIDE', '', NULL, '', 'Low' ),
( 'IT MTX & GCLAM', 'Multi', 'G-CLAM', ',mitoxantrone', NULL, ',IT MTX', 'High' ),
( 'GCLAM + HU', 'Multi', 'G-CLAM', ',mitoxantrone', NULL, ',hydroxyurea', 'High' ),
( 'GCLAM + GO', 'Multi', 'G-CLAM', ',mitoxantrone', NULL, ',gemtuzumab ozogamicin', 'High' ),
( 'GCLAM + Ara-C', 'Multi', 'G-CLAM', ',mitoxantrone', NULL, '', 'High' ),
( 'GCLAM+GO+Ara-C', 'Multi', 'G-CLAM', ',mitoxantrone', NULL, ',gemtuzumab ozogamicin', 'High' ),
( '2734', 'Multi', 'G-CLAM', ',mitoxantrone', NULL, '', 'High' ),
( '2734 off', 'Multi', 'G-CLAM', ',mitoxantrone', NULL, '', 'High' ),
( '2734off', 'Multi', 'G-CLAM', ',mitoxantrone', NULL, '', 'High' ),
( 'GCLAM', 'Multi', 'G-CLAM', ',mitoxantrone', NULL, '', 'High' ),
( 'G-CLAM', 'Multi', 'G-CLAM', ',mitoxantrone', NULL, '', 'High' ),
( 'GCLAM + Aza', 'Multi', 'G-CLAM', ',mitoxantrone', NULL, ',azacitidine', 'High' ),
( 'GCLAM + sor', 'Multi', 'G-CLAM', ',mitoxantrone', NULL, ',sorafenib', 'High' ),
( 'GCLAM + VP', 'Multi', 'G-CLAM', ',mitoxantrone', NULL, ',vincristine,prednisone', 'High' ),
( 'GCLAM+GO', 'Multi', 'G-CLAM', ',mitoxantrone', NULL, ',gemtuzumab ozogamicin', 'High' ),
( 'GCLAM+sorafenib', 'Multi', 'G-CLAM', ',mitoxantrone', NULL, ',sorafenib', 'High' ),
( 'GCLAM+VP', 'Multi', 'G-CLAM', ',mitoxantrone', NULL, ',vincristine,predinsone', 'High' ),
( 'GCLAMoff', 'Multi', 'G-CLAM', ',mitoxantrone', NULL, '', 'High' ),
( 'GCLAMoff+Sorafinib', 'Multi', 'G-CLAM', ',mitoxantrone', NULL, ',sorafenib', 'High' ),
( 'GCLAC + Sorafinib', 'Multi', 'G-CLAC', '', NULL, ',sorafenib', 'High' ),
( '6562 (G-CLAC)', 'Multi', 'G-CLAC', '', NULL, '', 'High' ),
( '7144', 'Multi', 'G-CLAC', '', NULL, '', 'High' ),
( 'GCLAC', 'Multi', 'G-CLAC', '', NULL, '', 'High' ),
( 'G-CLAC', 'Multi', 'G-CLAC', '', NULL, '', 'High' ),
( 'GCLAC off', 'Multi', 'G-CLAC', '', NULL, '', 'High' ),
( 'GCLAC+GO', 'Multi', 'G-CLAC', '', NULL, ',gemtuzumab ozogamicin', 'High' ),
( 'GCLA', 'Multi', 'G-CLA', '', NULL, '', 'High' ),
( 'G-CLA', 'Multi', 'G-CLA', '', NULL, '', 'High' ),
( '2315', 'Multi', 'FLAM', '', NULL, '', 'High' ),
( 'FLAM', 'Multi', 'FLAM', '', NULL, '', 'High' ),
( 'FLAG Ida + GO', 'Multi', 'FLAG-IDA', ',idarubicin', NULL, ',gemtuzumab ozogamicin', 'High' ),
( 'decitabine+FLAG Ida', 'Multi', 'FLAG-IDA', ',idarubicin', NULL, ',decitabine', 'High' ),
( 'FLAG Ida', 'Multi', 'FLAG-IDA', ',idarubicin', NULL, '', 'High' ),
( 'FLAG+Ida', 'Multi', 'FLAG-IDA', ',idarubicin', NULL, '', 'High' ),
( 'FLAG-ida', 'Multi', 'FLAG-IDA', ',idarubicin', NULL, '', 'High' ),
( 'FLAG-ida +GO', 'Multi', 'FLAG-IDA', ',idarubicin', NULL, ',gemtuzumab ozogamicin', 'High' ),
( 'FLAG', 'Multi', 'FLAG', '', NULL, '', 'High' ),
( 'FLAG+GO', 'Multi', 'FLAG', '', NULL, ',gemtuzumab ozogamicin', 'High' ),
( 'Mito-FLAG', 'Multi', 'FLAG', '', NULL, ',mitoxantrone', 'High' ),
( '14070', 'Multi', 'MEC', '', NULL, ',eselectin', 'High' ),
( 'E-MEC', 'Multi', 'MEC', '', NULL, ',eselectin', 'High' ),
( 'E-selectin MEC', 'Multi', 'MEC', '', NULL, ',eselectin', 'High' ),
( 'MEC + e-selectin', 'Multi', 'MEC', '', NULL, ',eselectin', 'High' ),
( '2652', 'Multi', 'MEC', '', NULL, ',decitabine', 'High' ),
( '2652 off + sorafenib', 'Multi', 'MEC', '', NULL, ',sorafenib,decitabine', 'High' ),
( '2652(off)', 'Multi', 'MEC', '', NULL, ',decitabine', 'High' ),
( '2652off', 'Multi', 'MEC', '', NULL, ',decitabine', 'High' ),
( 'D MEC', 'Multi', 'MEC', '', NULL, ',decitabine', 'High' ),
( 'Decitabin MEC', 'Multi', 'MEC', '', NULL, ',decitabine', 'High' ),
( 'Decitabine + MEC', 'Multi', 'MEC', '', NULL, ',decitabine', 'High' ),
( 'D-MEC', 'Multi', 'MEC', '', NULL, ',decitabine', 'High' ),
( 'MEC + Decitabine', 'Multi', 'MEC', '', NULL, ',decitabine', 'High' ),
( 'MEC + Decitabine+Sorafinib', 'Multi', 'MEC', '', NULL, ',sorafenib,decitabine', 'High' ),
( 'MEC+GO+Decitabine', 'Multi', 'MEC', '', NULL, ',gemtuzumab ozogamicin,decitabine', 'High' ),
( 'D-GCLAM', 'Multi', 'D-GCLAM', ',mitoxantrone', NULL, ' ', 'High' ),
( 'D-GCLAM (simul)', 'Multi', 'D-GCLAM', ',mitoxantrone', NULL, ' ', 'High' ),
( 'D-GCLAM (split)', 'Multi', 'D-GCLAM', ',mitoxantrone', NULL, ' ', 'High' ),
( 'D-GCLAM + sorafenib', 'Multi', 'D-GCLAM', ',mitoxantrone', NULL, ',sorafenib', 'High' ),
( 'CLAMoff', 'Multi', 'CLAM', '', NULL, '', 'High' ),
( 'CLAG', 'Multi', 'CLAG', '', NULL, '', 'High' ),
( 'SWOG 0301 (CSA, daunorubicin, Ara-C, G-CSF)', 'Multi', 'HiDAC', ',daunorubicin', NULL, ',cyclosporin,gcsf', 'High' ),
( 'IA', 'Multi', 'HDAC', ',idarubicin', NULL, ',idarubicin', 'High' ),
( 'IA +Bortez', 'Multi', 'HDAC', ',idarubicin', NULL, ',idarubicin,bortezomib', 'High' ),
( 'IA+Sorafinib', 'Multi', 'HDAC', ',idarubicin', NULL, ',idarubicin,sorafenib', 'High' ),
( '3+araC(2)+prav', 'Multi', 'HDAC', '', NULL, ',pravastatin', 'High' ),
( 'LIST', 'Multi', 'HDAC', ',daunorubicin', NULL, ',cyclosporin,daunorubicin', 'High' ),
( 'List CSA', 'Multi', 'HDAC', ',daunorubicin', NULL, ',cyclosporin,daunorubicin', 'High' ),
( '2566(TA)', 'Multi', 'ARA-C', '', NULL, ',tosedostat', 'Intermediate' ),
( '2566', 'Multi', 'TOSEDOSTAT', '', NULL, ',decitabine vs arac', 'Intermediate' ),
( '2566(TD)', 'Multi', 'TOSEDOSTAT', '', NULL, ',decitabine vs arac', 'Intermediate' ),
( 'MVP16', 'Multi', 'MITOXANTRONE + ETOPOSIDE ', '', NULL, ' ', 'Intermediate' ),
( 'MVP16+Prava.+Sorafinib', 'Multi', 'MITOXANTRONE + ETOPOSIDE ', '', NULL, ',sorafenib,pravastatin', 'Intermediate' ),
( 'MVCSAp', 'Multi', 'MITOXANTRONE + ETOPOSIDE ', '', NULL, ',pravastatin,cyclosporine', 'Intermediate' ),
( 'Mito+VP16', 'Multi', 'MITOXANTRONE + ETOPOSIDE ', '', NULL, ',vincristine', 'Intermediate' ),
( 'sorafinib', 'Single', 'SORAFENIB', '', NULL, '', 'Unknown - Low' ),
( 'GCLAM low', 'Multi', 'G-CLAM mini', ',mitoxantrone', NULL, '', 'Intermediate' ),
( 'Epoch+GO', 'Multi', 'EPOCH', '', NULL, ',gemtuzumab ozogamicin', 'Intermediate' ),
( '2588', 'Multi', '7+3', '', NULL, ',deciatbine', 'Intermediate' ),
( '2588 off', 'Multi', '7+3', '', NULL, ',deciatbine', 'Intermediate' ),
( '2588(off)', 'Multi', '7+3', '', NULL, ',deciatbine', 'Intermediate' ),
( '2690', 'Single', 'SGN-CD33A', '', NULL, '', 'Low' ),
( 'SGN-CD33A', 'Single', 'SGN-CD33A', '', NULL, '', 'Low' ),
( 'SGN + 7 + 3', 'Single|Multi', 'SGN-CD33A|7+3', '', NULL, ',SGN-CD33A', 'Low' ),
( 'SGN+7+3', 'Single|Multi', 'SGN-CD33A|7+3', '', NULL, ',SGN-CD33A', 'Low' ),
( 'SGN-CD123A', 'Single|Multi', 'SGN-CD123A|SGN-CD123A', '', NULL, '', 'Low' ),
( '2246', 'Single', 'SB1518', '', NULL, '', 'Low' ),
( '2413', 'Multi', 'BEND-IDA', '', NULL, '', 'Intermediate' ),
( '2413-Bendamustine +Idaribicin', 'Multi', 'BEND-IDA', '', NULL, ' ', 'Intermediate' ),
( 'IA prava (SWOG)', 'Multi', '7+3', '', NULL, ',pravastatin', 'Intermediate' ),
( 'atra + arsenic + 7 + 3', 'Multi', '7+3', '', NULL, ',tretinoin,arsenic', 'Intermediate' ),
( '3+7+ATO+ATRA', 'Multi', '7+3', '', NULL, ',tretinoin,arsenic', 'Intermediate' ),
( '7+3 (ida/Ara-C) + Sorafinib', 'Multi', '7+3', ',idarubicin', NULL, ',sorafenib', 'Intermediate' ),
( '3+7 (ida/Ara-C)', 'Multi', '7+3', ',idarubicin', NULL, '', 'Intermediate' ),
( '7+3 (ida/Ara-C)', 'Multi', '7+3', ',idarubicin', NULL, '', 'Intermediate' ),
( 'Ara-C+3+7', 'Multi', 'HiDAC', ',idarubicin', '10', ',idarubicin', 'High' ),
( '3(90)+7 +prava (dauno)', 'Multi', '7+3', ',daunorubicin', '90', ',pravastatin', 'Intermediate' ),
( '3+7', 'Multi', '7+3', '', NULL, '', 'Intermediate' ),
( '3+7(90)', 'Multi', '7+3', ',daunorubicin', '90', '', 'Intermediate' ),
( '3+7(90) +VP', 'Multi', '7+3', ',daunorubicin', '90', ',vincristine,prednisone', 'Intermediate' ),
( '3+7(dauno)', 'Multi', '7+3', ',daunorubicin', NULL, '', 'Intermediate' ),
( '3+7(dauno.60)', 'Multi', '7+3', ',daunorubicin', '60', '', 'Intermediate' ),
( '3+7+ATRA', 'Multi', '7+3', '', NULL, ',tretinoin', 'Intermediate' ),
( '3+7+Bortez.', 'Multi', '7+3', '', NULL, ',bortezomib', 'Intermediate' ),
( '3+7+clad', 'Multi', '7+3', '', NULL, ',cladribine', 'Intermediate' ),
( '3+7+Cladrabine', 'Multi', '7+3', '', NULL, ',cladribine', 'Intermediate' ),
( '3+7+GO', 'Multi', '7+3', '', NULL, ',gemtuzumab ozogamicin', 'Intermediate' ),
( '3+7+GO(dauno)', 'Multi', '7+3', ',daunorubicin', NULL, ',gemtuzumab ozogamicin', 'Intermediate' ),
( '3+7+plerixifor', 'Multi', '7+3', '', NULL, ',plerixafor', 'Intermediate' ),
( '3+7+Pravastatin', 'Multi', '7+3', '', NULL, ',pravastatin', 'Intermediate' ),
( '3+7+Sorafinib', 'Multi', '7+3', '', NULL, ',sorafenib', 'Intermediate' ),
( '3+7+TKI', 'Multi', '7+3', '', NULL, ',tki', 'Intermediate' ),
( '3+7+Vincristine/dexamethasone', 'Multi', '7+3', '', NULL, ',vincristine,dexamethasone', 'Intermediate' ),
( '3+7+VP+Rituximab', 'Multi', '7+3', '', NULL, ',vincristine,prednisone,rituximab', 'Intermediate' ),
( '7+3', 'Multi', '7+3', '', NULL, '', 'Intermediate' ),
( '7+3 (dauno 90.)', 'Multi', '7+3', ',daunorubicin', '90', '', 'Intermediate' ),
( '7+3 (dauno.)', 'Multi', '7+3', ',daunorubicin', NULL, '', 'Intermediate' ),
( '7+3 (dauno.45)', 'Multi', '7+3', ',daunorubicin', '45', '', 'Intermediate' ),
( '7+3 Cren', 'Multi', '7+3', '', NULL, ',crenolanib', 'Intermediate' ),
( '9011', 'Multi', '7+3', ',daunorubicin', NULL, ',hydroxyorea', 'Intermediate' ),
( 'Aza+3+7(dauno)', 'Multi', '7+3', ',daunorubicin', NULL, ',azacitidine', 'Intermediate' ),
( 'AZA-3+7', 'Multi', '7+3', '', NULL, ',azacitidine', 'Intermediate' ),
( 'deci + 3+7', 'Multi', '7+3', '', NULL, ',decitabine', 'Intermediate' ),
( 'deci + 3+7 (ida)', 'Multi', '7+3', ',idarubicin', NULL, ',decitabine', 'Intermediate' ),
( 'Decit+3+7 (Dauno 45)', 'Multi', '7+3', ',daunorubicin', '45', ',decitabine', 'Intermediate' ),
( 'feldman-3+7(aza)', 'Multi', '7+3', '', NULL, ',azacitadine', 'Intermediate' ),
( 'Feldman-3+7(dect.)', 'Multi', '7+3', '', NULL, ',decitabine', 'Intermediate' ),
( 'FLT3 ITD + 7 + 3 + Cren', 'Multi', '7+3', '', NULL, ',crenolanib', 'Intermediate' ),
( 'SO106', 'Multi', '7+3', '', NULL, ',without gemtuzumab ozogamicin', 'Intermediate' ),
( 'SO106+GO', 'Multi', '7+3', '', NULL, ',gemtuzumab ozogamicin', 'Intermediate' ),
( 'SWOG 0106 (7+3 without GO)', 'Multi', '7+3', '', NULL, ',without gemtuzumab ozogamicin', 'Intermediate' ),
( 'SWOG 0106 (7+3+GO)', 'Multi', '7+3', '', NULL, ',gemtuzumab ozogamicin', 'Intermediate' ),
( '5+2', 'Multi', '5+2', '', NULL, '', 'Intermediate' ),
( '2409', 'Multi', 'MITOXANTRONE + ETOPOSIDE ', '', NULL, ',pravastatin,cyclosporine', 'Intermediate' ),
( '2409 off', 'Multi', 'MITOXANTRONE + ETOPOSIDE ', '', NULL, ',pravastatin,cyclosporine', 'Intermediate' ),
( '9233', 'Multi', '7+3', '', NULL, 'SGN-CD33A', 'Intermediate' ),
( '9351', 'Multi', '7+3', '', NULL, ',crenolanib', 'Intermediate' ),
( 'SWOG 0601', 'Multi', '7+3', '', NULL, '', 'intermediate' ),
( 'Ida+ATRA', 'Multi', 'ATRA', ',idarubicin', NULL, '', 'Intermediate' ),
( 'MOMVSRUX', 'Single', 'RUXOLITINIB', '', NULL, '', 'Low' ),
( 'HAM-S+Vincristine', 'Multi', 'HAM', '', NULL, ',vincristine', 'Intermediate' ),
( 'HCVAD', 'Multi', 'HYPERCVAD', '', NULL, '', 'Intermediate' ),
( 'HYPERCVAD', 'Multi', 'HYPERCVAD', '', NULL, '', 'Intermediate' ),
( 'MVP', 'Multi', 'METHOTREXATE,PROCARBAZINE,VINCRISTINE', '', NULL, '', 'Intermediate' ),
( 'ME + PRAV', 'Multi', 'MITOXANTRONE + ETOPOSIDE ', '', NULL, ',pravastatin', 'Intermediate' ),
( 'Mitoxa.. + Etoposide', 'Multi', 'MITOXANTRONE + ETOPOSIDE ', '', NULL, '', 'Intermediate' ),
( 'MV + prava', 'Multi', 'MITOXANTRONE + ETOPOSIDE ', '', NULL, ',pravastatin', 'Intermediate' ),
( 'MV+CEP', 'Multi', 'MITOXANTRONE + ETOPOSIDE ', '', NULL, ',cep FLT3 drug', 'Intermediate' ),
( 'Pravastatin, Mitoxantrone and Etoposide', 'Multi', 'MITOXANTRONE + ETOPOSIDE ', '', NULL, ',pravastatin', 'Intermediate' ),
( 'PR104', 'Single', 'PR104', '', NULL, '', 'Low' ),
( '2532', 'Single', 'PLX3397', '', NULL, '', 'Low' ),
( 'DNR +IDAC', 'Multi', 'ARA-C', ',daunorubicin', NULL, ',daunorubicin', 'Intermediate' ),
( 'decitabine + EC', 'Multi', 'ARA-C', '', NULL, ',decitabine,etoposide', 'High' ),
( 'MTX +Asparaginase', 'Multi', 'ASPARAGINASE ', '', NULL, ',methotrexate', 'Intermediate' ),
( 'CLO-24300606', 'Multi', 'CLOFARABINE', '', NULL, '', 'Intermediate' ),
( 'gemcitabine and docetaxel', 'Multi', 'GEMCITABINE', '', NULL, ',docetaxel', 'Intermediate' ),
( 'gemcitabine/docetaxol', 'Multi', 'GEMCITABINE', '', NULL, ',docetaxel', 'Intermediate' ),
( '2534', 'Single|Multi', 'ON 01910.Na (2534)|LDAC', '', NULL, '', 'Low' ),
( 'Nalarabine', 'Single', 'NALARABINE', '', NULL, '', 'Low' ),
( '09036', 'Single', 'MDX-1338', '', NULL, '', 'Low' ),
( '9036', 'Single', 'MDX-1338', '', NULL, '', 'Low' ),
( 'Lenalidomide', 'Single', 'LENALIDOMIDE ', '', NULL, ' ', 'Low' ),
( 'LDAC', 'Single', 'LDAC', '', NULL, '', 'Low' ),
( 'IT-ara-C(lipo)', 'Single', 'IT-ARA-C', '', NULL, '', 'IT' ),
( 'XRT + AZA', 'Multi', 'AZA', '', NULL, ',XRT', 'Low' ),
( 'WIS', 'Multi', 'Withdrawal Immunosuppression', '', NULL, '', 'Low' ),
( 'GO +SAHA', 'Multi', 'VORINO+GO', '', NULL, '', 'Low' ),
( '2200', 'Multi', 'VORINO+GO', '', NULL, '', 'Low' ),
( 'Vorino+GO', 'Multi', 'VORINO+GO', '', NULL, '', 'Low' ),
( ' IT triple rx + cranial XRT', 'Single', 'IT ', '', NULL, ',ITtriple,XRTcranial', 'IT' ),
( '2690(+aza)', 'Multi', 'SGN-CD33A', '', NULL, ',azacitidine', 'Low' ),
( 'IT MTX', 'Single', 'IT', '', NULL, ',methotrexateIT', 'IT' ),
( 'IT MTX + Radiation', 'Single', 'IT', '', NULL, ',methotrexateIT', 'IT' ),
( '13049', 'Single', 'IGN-523', '', NULL, '', 'Low' ),
( 'UW 13049  with IGN-523', 'Single', 'IGN-523', '', NULL, '', 'Low' ),
( 'idarubicin', 'Single', 'IDARUBICIN', '', NULL, '', 'Intermediate' ),
( 'Iburtinib', 'Single', 'IBRUTINIB', '', NULL, '', 'Low' ),
( 'HU', 'Single', 'HYDROXYUREA', '', NULL, '', 'Low' ),
( '2466', 'Multi', 'MEK INHIBITOR', '', NULL, '', 'Low' ),
( 'MEK', 'Multi', 'MEK INHIBITOR', '', NULL, '', 'Low' ),
( 'MEK inhibitor', 'Multi', 'MEK INHIBITOR', '', NULL, '', 'Low' ),
( 'Aza + Lenalidomide', 'Multi', 'AZA', '', NULL, ',lenalidomide', 'Low' ),
( '2411-HiDAC only', 'Single', 'HiDAC', '', NULL, '', 'High' ),
( 'deci + LDAC', 'Multi', 'LDAC', '', NULL, ',decitabine', 'Low' ),
( 'LDAC + sorafenib', 'Multi', 'LDAC', '', NULL, ',sorafenib', 'Low' ),
( 'HiDAC', 'Single', 'HiDAC', '', NULL, '', 'High' ),
( '2592', 'Single|Multi', 'HEDGEHOG|HEDGEHOG', '', NULL, '', 'Low' ),
( '2592-Hedgehog inhibitor', 'Single|Multi', 'HEDGEHOG|HEDGEHOG', '', NULL, '', 'Low' ),
( 'Hedgehog inhibitor', 'Single|Multi', 'HEDGEHOG|HEDGEHOG', '', NULL, '', 'Low' ),
( 'HU + Sorafen', 'Multi', 'HYDROXYUREA', '', NULL, ',sorafenib', 'Low' ),
( '7971', 'Single', 'GO', '', NULL, '', 'Low' ),
( 'GO', 'Single', 'GO', '', NULL, '', 'Low' ),
( 'FLX', 'Single', 'FLX925', '', NULL, '', 'Low' ),
( 'DAC', 'Single', 'DECITABINE', '', NULL, '', 'Low' ),
( 'DAC + Go', 'Multi', 'DECITABINE', '', NULL, ',gemtuzumab ozogamicin', 'Low' ),
( 'DACOGEN + GO', 'Multi', 'DECITABINE', '', NULL, ',gemtuzumab ozogamicin', 'Low' ),
( 'Decitabin + GO', 'Multi', 'DECITABINE', '', NULL, ',gemtuzumab ozogamicin', 'Low' ),
( 'DACOGEN', 'Single', 'DECITABINE', '', NULL, '', 'Low' ),
( 'Decitabin', 'Single', 'DECITABINE', '', NULL, '', 'Low' ),
( 'Decitabine', 'Single', 'DECITABINE', '', NULL, '', 'Low' ),
( '9019', 'Multi', 'DECITABINE+ARA-C', '', NULL, '', 'Low' ),
( '9019off', 'Multi', 'DECITABINE+ARA-C', '', NULL, '', 'Low' ),
( '6TG + Decitabine', 'Multi', 'DECITABINE', '', NULL, ',thioguanine', 'Low' ),
( 'Decitabin + Rituximab', 'Multi', 'DECITABINE', '', NULL, ',rituximab', 'Low' ),
( 'decitabin+Imatinib', 'Multi', 'DECITABINE', '', NULL, ',imatinib', 'Low' ),
( 'decitabine+thioguanine', 'Multi', 'DECITABINE', '', NULL, ',thioguanine', 'Low' ),
( 'Act-D', 'Single', 'DACTINOMYCIN', '', NULL, '', 'Low' ),
( 'actinomycin + hydroxyurea', 'Single', 'DACTINOMYCIN', '', NULL, ',hydroxyurea', 'Low' ),
( '2513', 'Single', 'CWP', '', NULL, '', 'Low' ),
( '2513off', 'Single', 'CWP', '', NULL, '', 'Low' ),
( '2651', 'Single', 'CPX-351', '', NULL, '', 'Intermediate' ),
( 'cpx-351', 'Single', 'CPX-351', '', NULL, '', 'Intermediate' ),
( 'CPX-351 (2642)', 'Single', 'CPX-351', '', NULL, '', 'Intermediate' ),
( '2642', 'Single', 'CPX-351', '', NULL, '', 'Intermediate' ),
( 'clofarabine and LDAC', 'Multi', 'CLOFARABINE+LDAC', '', NULL, ' ', 'Low' ),
( 'I.V.clofarabine and LDAC', 'Multi', 'CLOFARABINE+LDAC', '', NULL, '', 'Low' ),
( 'IV-clofarabine and LDAC', 'Multi', 'CLOFARABINE+LDAC', '', NULL, '', 'Low' ),
( 'Oral-clofarabine and LDAC', 'Multi', 'CLOFARABINE+LDAC', '', NULL, '', 'Low' ),
( '2302', 'Multi', 'CLOFARABINE+LDAC', '', NULL, '', 'Low' ),
( 'Consult', 'Single', 'Consult only, no treatment', '', NULL, '', 'Supportive' ),
( 'UKN', 'Single', 'Consult only, no treatment', '', NULL, '', 'Supportive' ),
( 'UKN yet', 'Single', 'Consult only, no treatment', '', NULL, '', 'Supportive' ),
( 'Aza + Vorinostat', 'Multi', 'AZA+VORINOSTAT', '', NULL, '', 'Low' ),
( '2288', 'Multi', 'AZA+GO+VORINOSTAT', '', NULL, '', 'Low' ),
( 'AZA+GO+vorinostat', 'Multi', 'AZA+GO+VORINOSTAT', '', NULL, '', 'Low' ),
( 'aza +/- birin', 'Multi', 'AZA', '', NULL, ',vorinostat', 'Low' ),
( 'Aza+Dactinomycin', 'Multi', 'AZA', '', NULL, ',dactinomycin', 'Low' ),
( 'AZA+GO', 'Multi', 'AZA', '', NULL, ',gemtuzumab ozogamicin', 'Low' ),
( 'AZA+GO+sorafinib', 'Multi', 'AZA', '', NULL, ',gemtuzumab ozogamicin,sorafenib', 'Low' ),
( 'AZA+PDL1', 'Multi', 'AZA', '', NULL, ',PDL1', 'Low' ),
( 'AZA+Romiplastin', 'Multi', 'AZA', '', NULL, ',romiplastin', 'Low' ),
( 'AZA+sorafenib', 'Multi', 'AZA', '', NULL, ',sorafenib', 'Low' ),
( 'Unknown', 'Single', 'Consult only, no treatment', '', NULL, '', 'Supportive' ),
( 'Outside Rx.', 'Single', 'Consult only, no treatment', '', NULL, '', 'Supportive' ),
( 'Clofarabine', 'Single', 'CLOFARABINE', '', NULL, ' ', 'Intermediate' ),
( 'Atra, ATO + GO', 'Multi', 'ATRA', '', NULL, ',gemtuzumab ozogamicin,arsenic', 'Low' ),
( 'Atra + arsenic', 'Multi', 'ATRA', '', NULL, ',arsenic', 'low' ),
( 'ATRA and arsenic with dexamethasone', 'Multi', 'ATRA', '', NULL, ',arsenic', 'low' ),
( 'AA+GO', 'Multi', 'ATRA', '', NULL, ',gemtuzumab ozogamicin ', 'low' ),
( 'Arsenic+ATRA', 'Multi', 'ATRA', '', NULL, ',arsenic', 'low' ),
( 'Arsenic+ATRA+ida', 'Multi', 'ATRA', ',idarubicin', NULL, ',idarubicin,arsenic', 'low' ),
( 'ATO+ATRA', 'Multi', 'ATRA', '', NULL, ',arsenic', 'low' ),
( 'ATO+ATRA+ida', 'Multi', 'ATRA', '', NULL, ',arsenic', 'low' ),
( 'Cladrabine', 'Single', 'CLADRABINE', '', NULL, ' ', 'Intermediate' ),
( 'decitabin + cytarabine', 'Multi', 'DECITABINE+ARA-C', '', NULL, ' ', 'Low' ),
( 'decitabine+Ara-C', 'Multi', 'DECITABINE+ARA-C', '', NULL, ' ', 'Low' ),
( 'Decitabine+Cytarabine', 'Multi', 'DECITABINE+ARA-C', '', NULL, ' ', 'Low' ),
( 'CEP701', 'Single', 'CEP701 - FLT3 drug', '', NULL, ' ', 'Low' ),
( 'AMG-232 + tremetnib', 'Multi', 'AMG-232', '', NULL, ',tremetnib', 'Low' ),
( 'Bortezomib', 'Single', 'BORTEZOMIB', '', NULL, ' ', 'Low' ),
( '11003', 'Single', 'BMN (UW11003)', '', NULL, '', 'Low' ),
( 'Aza', 'Single', 'AZA', '', NULL, '', 'Low' ),
( 'Azacitidine', 'Single', 'AZA', '', NULL, '', 'Low' ),
( 'Vidaza', 'Single', 'AZA', '', NULL, '', 'Low' ),
( 'ATRA', 'Single', 'ATRA', '', NULL, '', 'Low' ),
( 'IT-ara-C', 'Single', 'ARA-C IT', '', NULL, '', 'IT' ),
( 'Ara-C', 'Single', 'ARA-C', '', NULL, ' ', 'Intermediate' ),
( 'cytarabine only', 'Single', 'ARA-C', '', NULL, ' ', 'Intermediate' ),
( 'Liposomal Cytarabine', 'Single', 'ARA-C', '', NULL, ' ', 'IT' ),
( 'amg 330', 'Single', 'AMG-330', '', NULL, '', 'Low' ),
( '13037', 'Single', 'AMG-232', '', NULL, '', 'Low' ),
( 'ATRA+GO', 'Multi', 'ATRA', '', NULL, ',gemtuzumab ozogamicin ', 'Low' ),
( 'S0919', 'Multi', 'DECITABINE+ARA-C', '', NULL, '', 'Low' ),
( 'Jak-2', 'Multi', 'JAK-2', '', NULL, '', 'Low' ),
( 'ruxolitinib+HU', 'Multi', 'RUXOLITINIB', '', NULL, ',hydroxyurea', 'Low' ),
( 'AMG 232', 'Single', 'AMG-232', '', NULL, '', 'Low' ),
( 'AMG-232', 'Single', 'AMG-232', '', NULL, '', 'Low' ),
( 'UW 13037', 'Single', 'AMG-232', '', NULL, '', 'Low' ),
( 'revlamid', 'Multi', 'REVLAMID', '', NULL, '', 'Low' ),
( 'Pralatrexate', 'Multi', 'PRALATREXATE', '', NULL, '', 'Low' ),
( 'GO + 1432', 'Multi', 'HCT', '', NULL, ',gemtuzumab ozogamicin', 'Other' ),
( '2206', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( '2222', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( ' CD45Ydotabiotin', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( '131 HCT', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( '131 ICD45', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( '131I + Fludarabine', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( '1931', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( '2010', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( '2044', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( '2130', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( '2186', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( '2309', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( '2335', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( '2468', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( '2524', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( '739', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( '7617', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( 'AC220', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( 'Bu-CY', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( 'CD45I131', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( 'Cy + TBI', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( 'FLU + TBI', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( 'FLU + TBI (3Gy)', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( 'FLU TREO', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( 'Flu/By', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( 'HCT', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( 'HCT 7617', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( 'HCT I-131', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( 'HSCT', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( 'I131 Allo', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( 'i131 haplo', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( 'PBMTC GVH 1201', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( 'TBI', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( 'Y-DOTA', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( '2498', 'Multi', 'CD8+ T Cells (2498)', '', NULL, '', 'Other' ),
( '1641/1938', 'Multi', 'HCT', '', NULL, '', 'Other' ),
( '7910', 'Multi', 'OUTPATIENT INDUCTION', '', NULL, '', 'Other' ),
( '8003', 'Multi', 'PICKaDRUG', '', NULL, '', 'Other' ),
( '9226', 'Multi', 'PICKaDRUG', '', NULL, '', 'Other' ),
( '2661', 'Multi', 'RANDOMIZE MDS VS AML TX', '', NULL, '', 'Other' ),
( 'Radiation +Chemo', 'Multi', 'RXT + Chemo', '', NULL, '', 'Other' ),
( 'Hospice', 'Multi', 'PALLIATIVE/HOSPICE', '', NULL, '', 'Supportive' ),
( 'HU/Palliative', 'Multi', 'PALLIATIVE/HOSPICE', '', NULL, ',hydroxyurea', 'Supportive' ),
( 'Palliative Care', 'Multi', 'PALLIATIVE/HOSPICE', '', NULL, '', 'Supportive' ),
( 'OsteoK', 'Multi', 'PALLIATIVE/HOSPICE', '', NULL, ',OSTEOK', 'Supportive' ),
( 'No Treatment', 'Multi', 'PALLIATIVE/HOSPICE', '', NULL, '', 'Supportive' ),
( 'ADCT-301', 'Single', 'ADCT-301', '', NULL, '', 'Low' ),
( '2572', 'Single', 'AC-225', '', NULL, '', 'Low' ),
( 'Ara-C + ABT', 'Single|Multi', 'ABT-199|ABT199', '', NULL, ',cytarabine', 'Low' ),
( '14053', 'Single|Multi', 'ABT-199|ABT199', '', NULL, ',azacitadine', 'Low' ),
( '9237', 'Single|Multi', 'ABT-199|ABT199', '', NULL, ',cytarabine', 'Low' ),
( 'Ara-C + Sorafinib', 'Multi', 'ARA-C', '', NULL, ',sorafenib', 'Unknown' ),
( 'ibrutinib + Ara-C', 'Multi', 'ARA-C', '', NULL, ',ibrutinib', 'Low' ),
( 'iburtinib + Ara-C', 'Multi', 'ARA-C', '', NULL, ',ibrutinib', 'Low' ),
( 'Ara-C + Mitoxantrone', 'Multi', 'ARA-C', ',mitoxantrone', NULL, ',mitoxantrone', 'Unknown' ),
( 'Ara-C + Pravastatin', 'Multi', 'ARA-C', '', NULL, ',pravastatin', 'Unknown' ),
( 'Ara-C +GO', 'Multi', 'ARA-C', '', NULL, ',gemtuzumab ozogamicin', 'Unknown' ),
( 'Ara-C+CEP', 'Multi', 'ARA-C', '', NULL, ',lestaurtinib', 'High' ),
( 'Ara-C+HU', 'Multi', 'ARA-C', '', NULL, ',hydroxyurea', 'High' ),
( 'cladribine-Ara C', 'Multi', 'ARA-C', '', NULL, ',cladribine', 'Intermediate' ),
( 'Cytarabine+Idriamycin', 'Multi', 'ARA-C', ',idarubicin', NULL, ',idarubicin', 'Unknown' ),
( 'etoposide and cytarabine', 'Multi', 'ARA-C', '', NULL, ',etoposide,decitabine', 'Intermediate' ),
( 'SWOG S0117 (Mylotarg; Ara-C)', 'Multi', 'ARA-C', '', NULL, ',gemtuzumab ozogamicin', 'Unknown' ),
( 'Aza + Sorafinib', 'Multi', 'AZA', '', NULL, ',sorafenib', 'Unknown - Low' ),
( 'ABT + Aza', 'Single|Multi', 'ABT-199|ABT199', '', NULL, ',azacitadine', 'Low' ),
( 'SO521', 'Multi', 'ATRA', ',daunorubicin', NULL, ',cytarabine,daunorubicin', 'Intermediate' );

DROP TABLE IF EXISTS temp.BackBoneMappingFailures;
CREATE TABLE temp.BackBoneMappingFailures
    SELECT SPACE(100) AS TentativeBackBoneMapping,
            UPPER(a.MedTxAgent) AS MedTxAgent
            , MedTxDate
            , b.* 
        FROM caisis.vdatasetmedicaltherapy a
        LEFT JOIN caisis.backbonemapping b
        ON UPPER(a.MedTxAgent) = b.OriginalProtocol
        WHERE a.MedTxDisease LIKE '%AML%';


UPDATE temp.BackBoneMappingFailures
    SET TentativeBackBoneMapping = '';